/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppDatabaseSetupAnswer
 */
export interface AppDatabaseSetupAnswer {
    /**
     * 
     * @type {string}
     * @memberof AppDatabaseSetupAnswer
     */
    questionId: string;
    /**
     * 
     * @type {string}
     * @memberof AppDatabaseSetupAnswer
     */
    text: string;
    /**
     * 
     * @type {string}
     * @memberof AppDatabaseSetupAnswer
     */
    id?: string;
}

/**
 * Check if a given object implements the AppDatabaseSetupAnswer interface.
 */
export function instanceOfAppDatabaseSetupAnswer(value: object): value is AppDatabaseSetupAnswer {
    if (!('questionId' in value) || value['questionId'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function AppDatabaseSetupAnswerFromJSON(json: any): AppDatabaseSetupAnswer {
    return AppDatabaseSetupAnswerFromJSONTyped(json, false);
}

export function AppDatabaseSetupAnswerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppDatabaseSetupAnswer {
    if (json == null) {
        return json;
    }
    return {
        
        'questionId': json['question_id'],
        'text': json['text'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function AppDatabaseSetupAnswerToJSON(json: any): AppDatabaseSetupAnswer {
    return AppDatabaseSetupAnswerToJSONTyped(json, false);
}

export function AppDatabaseSetupAnswerToJSONTyped(value?: AppDatabaseSetupAnswer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'question_id': value['questionId'],
        'text': value['text'],
        'id': value['id'],
    };
}

