/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TopicExtended } from './TopicExtended';
import {
    TopicExtendedFromJSON,
    TopicExtendedFromJSONTyped,
    TopicExtendedToJSON,
    TopicExtendedToJSONTyped,
} from './TopicExtended';

/**
 * 
 * @export
 * @interface DetailedAnalysis
 */
export interface DetailedAnalysis {
    /**
     * 
     * @type {Array<TopicExtended>}
     * @memberof DetailedAnalysis
     */
    topics: Array<TopicExtended>;
}

/**
 * Check if a given object implements the DetailedAnalysis interface.
 */
export function instanceOfDetailedAnalysis(value: object): value is DetailedAnalysis {
    if (!('topics' in value) || value['topics'] === undefined) return false;
    return true;
}

export function DetailedAnalysisFromJSON(json: any): DetailedAnalysis {
    return DetailedAnalysisFromJSONTyped(json, false);
}

export function DetailedAnalysisFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailedAnalysis {
    if (json == null) {
        return json;
    }
    return {
        
        'topics': ((json['topics'] as Array<any>).map(TopicExtendedFromJSON)),
    };
}

export function DetailedAnalysisToJSON(json: any): DetailedAnalysis {
    return DetailedAnalysisToJSONTyped(json, false);
}

export function DetailedAnalysisToJSONTyped(value?: DetailedAnalysis | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'topics': ((value['topics'] as Array<any>).map(TopicExtendedToJSON)),
    };
}

