/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AnswerPublicExtended } from './AnswerPublicExtended';
import {
    AnswerPublicExtendedFromJSON,
    AnswerPublicExtendedFromJSONTyped,
    AnswerPublicExtendedToJSON,
    AnswerPublicExtendedToJSONTyped,
} from './AnswerPublicExtended';
import type { TopicExtended } from './TopicExtended';
import {
    TopicExtendedFromJSON,
    TopicExtendedFromJSONTyped,
    TopicExtendedToJSON,
    TopicExtendedToJSONTyped,
} from './TopicExtended';
import type { Summary } from './Summary';
import {
    SummaryFromJSON,
    SummaryFromJSONTyped,
    SummaryToJSON,
    SummaryToJSONTyped,
} from './Summary';

/**
 * 
 * @export
 * @interface FullQuestionAnalysis
 */
export interface FullQuestionAnalysis {
    /**
     * 
     * @type {Summary}
     * @memberof FullQuestionAnalysis
     */
    summary: Summary | null;
    /**
     * 
     * @type {Array<AnswerPublicExtended>}
     * @memberof FullQuestionAnalysis
     */
    answers: Array<AnswerPublicExtended>;
    /**
     * 
     * @type {Array<TopicExtended>}
     * @memberof FullQuestionAnalysis
     */
    topics: Array<TopicExtended>;
}

/**
 * Check if a given object implements the FullQuestionAnalysis interface.
 */
export function instanceOfFullQuestionAnalysis(value: object): value is FullQuestionAnalysis {
    if (!('summary' in value) || value['summary'] === undefined) return false;
    if (!('answers' in value) || value['answers'] === undefined) return false;
    if (!('topics' in value) || value['topics'] === undefined) return false;
    return true;
}

export function FullQuestionAnalysisFromJSON(json: any): FullQuestionAnalysis {
    return FullQuestionAnalysisFromJSONTyped(json, false);
}

export function FullQuestionAnalysisFromJSONTyped(json: any, ignoreDiscriminator: boolean): FullQuestionAnalysis {
    if (json == null) {
        return json;
    }
    return {
        
        'summary': SummaryFromJSON(json['summary']),
        'answers': ((json['answers'] as Array<any>).map(AnswerPublicExtendedFromJSON)),
        'topics': ((json['topics'] as Array<any>).map(TopicExtendedFromJSON)),
    };
}

export function FullQuestionAnalysisToJSON(json: any): FullQuestionAnalysis {
    return FullQuestionAnalysisToJSONTyped(json, false);
}

export function FullQuestionAnalysisToJSONTyped(value?: FullQuestionAnalysis | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'summary': SummaryToJSON(value['summary']),
        'answers': ((value['answers'] as Array<any>).map(AnswerPublicExtendedToJSON)),
        'topics': ((value['topics'] as Array<any>).map(TopicExtendedToJSON)),
    };
}

