/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProcessingDefinitionsAnswer
 */
export interface ProcessingDefinitionsAnswer {
    /**
     * 
     * @type {string}
     * @memberof ProcessingDefinitionsAnswer
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ProcessingDefinitionsAnswer
     */
    text: string;
}

/**
 * Check if a given object implements the ProcessingDefinitionsAnswer interface.
 */
export function instanceOfProcessingDefinitionsAnswer(value: object): value is ProcessingDefinitionsAnswer {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function ProcessingDefinitionsAnswerFromJSON(json: any): ProcessingDefinitionsAnswer {
    return ProcessingDefinitionsAnswerFromJSONTyped(json, false);
}

export function ProcessingDefinitionsAnswerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessingDefinitionsAnswer {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'text': json['text'],
    };
}

export function ProcessingDefinitionsAnswerToJSON(json: any): ProcessingDefinitionsAnswer {
    return ProcessingDefinitionsAnswerToJSONTyped(json, false);
}

export function ProcessingDefinitionsAnswerToJSONTyped(value?: ProcessingDefinitionsAnswer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'text': value['text'],
    };
}

