/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QuestionUpdate
 */
export interface QuestionUpdate {
    /**
     * 
     * @type {string}
     * @memberof QuestionUpdate
     */
    text?: string | null;
}

/**
 * Check if a given object implements the QuestionUpdate interface.
 */
export function instanceOfQuestionUpdate(value: object): value is QuestionUpdate {
    return true;
}

export function QuestionUpdateFromJSON(json: any): QuestionUpdate {
    return QuestionUpdateFromJSONTyped(json, false);
}

export function QuestionUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'] == null ? undefined : json['text'],
    };
}

export function QuestionUpdateToJSON(json: any): QuestionUpdate {
    return QuestionUpdateToJSONTyped(json, false);
}

export function QuestionUpdateToJSONTyped(value?: QuestionUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
    };
}

