/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QuestionCreate
 */
export interface QuestionCreate {
    /**
     * 
     * @type {string}
     * @memberof QuestionCreate
     */
    quizId: string;
    /**
     * 
     * @type {string}
     * @memberof QuestionCreate
     */
    text: string;
}

/**
 * Check if a given object implements the QuestionCreate interface.
 */
export function instanceOfQuestionCreate(value: object): value is QuestionCreate {
    if (!('quizId' in value) || value['quizId'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function QuestionCreateFromJSON(json: any): QuestionCreate {
    return QuestionCreateFromJSONTyped(json, false);
}

export function QuestionCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'quizId': json['quiz_id'],
        'text': json['text'],
    };
}

export function QuestionCreateToJSON(json: any): QuestionCreate {
    return QuestionCreateToJSONTyped(json, false);
}

export function QuestionCreateToJSONTyped(value?: QuestionCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'quiz_id': value['quizId'],
        'text': value['text'],
    };
}

