/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QuestionPublic } from './QuestionPublic';
import {
    QuestionPublicFromJSON,
    QuestionPublicFromJSONTyped,
    QuestionPublicToJSON,
    QuestionPublicToJSONTyped,
} from './QuestionPublic';

/**
 * 
 * @export
 * @interface QuizPublic
 */
export interface QuizPublic {
    /**
     * 
     * @type {string}
     * @memberof QuizPublic
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof QuizPublic
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof QuizPublic
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof QuizPublic
     */
    userId: string;
    /**
     * 
     * @type {Array<QuestionPublic>}
     * @memberof QuizPublic
     */
    questions?: Array<QuestionPublic>;
}

/**
 * Check if a given object implements the QuizPublic interface.
 */
export function instanceOfQuizPublic(value: object): value is QuizPublic {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function QuizPublicFromJSON(json: any): QuizPublic {
    return QuizPublicFromJSONTyped(json, false);
}

export function QuizPublicFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuizPublic {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'],
        'userId': json['user_id'],
        'questions': json['questions'] == null ? undefined : ((json['questions'] as Array<any>).map(QuestionPublicFromJSON)),
    };
}

export function QuizPublicToJSON(json: any): QuizPublic {
    return QuizPublicToJSONTyped(json, false);
}

export function QuizPublicToJSONTyped(value?: QuizPublic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'id': value['id'],
        'user_id': value['userId'],
        'questions': value['questions'] == null ? undefined : ((value['questions'] as Array<any>).map(QuestionPublicToJSON)),
    };
}

