/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QuizCreate
 */
export interface QuizCreate {
    /**
     * 
     * @type {string}
     * @memberof QuizCreate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof QuizCreate
     */
    description?: string | null;
}

/**
 * Check if a given object implements the QuizCreate interface.
 */
export function instanceOfQuizCreate(value: object): value is QuizCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function QuizCreateFromJSON(json: any): QuizCreate {
    return QuizCreateFromJSONTyped(json, false);
}

export function QuizCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuizCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function QuizCreateToJSON(json: any): QuizCreate {
    return QuizCreateToJSONTyped(json, false);
}

export function QuizCreateToJSONTyped(value?: QuizCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

