/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RatingCreate
 */
export interface RatingCreate {
    /**
     * 
     * @type {string}
     * @memberof RatingCreate
     */
    quizId: string;
    /**
     * 
     * @type {string}
     * @memberof RatingCreate
     */
    question: string;
    /**
     * 
     * @type {number}
     * @memberof RatingCreate
     */
    starsGiven: number;
}

/**
 * Check if a given object implements the RatingCreate interface.
 */
export function instanceOfRatingCreate(value: object): value is RatingCreate {
    if (!('quizId' in value) || value['quizId'] === undefined) return false;
    if (!('question' in value) || value['question'] === undefined) return false;
    if (!('starsGiven' in value) || value['starsGiven'] === undefined) return false;
    return true;
}

export function RatingCreateFromJSON(json: any): RatingCreate {
    return RatingCreateFromJSONTyped(json, false);
}

export function RatingCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatingCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'quizId': json['quiz_id'],
        'question': json['question'],
        'starsGiven': json['stars_given'],
    };
}

export function RatingCreateToJSON(json: any): RatingCreate {
    return RatingCreateToJSONTyped(json, false);
}

export function RatingCreateToJSONTyped(value?: RatingCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'quiz_id': value['quizId'],
        'question': value['question'],
        'stars_given': value['starsGiven'],
    };
}

