/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RatingPublic
 */
export interface RatingPublic {
    /**
     * 
     * @type {string}
     * @memberof RatingPublic
     */
    quizId: string;
    /**
     * 
     * @type {string}
     * @memberof RatingPublic
     */
    question: string;
    /**
     * 
     * @type {number}
     * @memberof RatingPublic
     */
    starsGiven: number;
    /**
     * 
     * @type {string}
     * @memberof RatingPublic
     */
    id: string;
}

/**
 * Check if a given object implements the RatingPublic interface.
 */
export function instanceOfRatingPublic(value: object): value is RatingPublic {
    if (!('quizId' in value) || value['quizId'] === undefined) return false;
    if (!('question' in value) || value['question'] === undefined) return false;
    if (!('starsGiven' in value) || value['starsGiven'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function RatingPublicFromJSON(json: any): RatingPublic {
    return RatingPublicFromJSONTyped(json, false);
}

export function RatingPublicFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatingPublic {
    if (json == null) {
        return json;
    }
    return {
        
        'quizId': json['quiz_id'],
        'question': json['question'],
        'starsGiven': json['stars_given'],
        'id': json['id'],
    };
}

export function RatingPublicToJSON(json: any): RatingPublic {
    return RatingPublicToJSONTyped(json, false);
}

export function RatingPublicToJSONTyped(value?: RatingPublic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'quiz_id': value['quizId'],
        'question': value['question'],
        'stars_given': value['starsGiven'],
        'id': value['id'],
    };
}

