/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseBase
 */
export interface ResponseBase {
    /**
     * 
     * @type {string}
     * @memberof ResponseBase
     */
    message: string;
}

/**
 * Check if a given object implements the ResponseBase interface.
 */
export function instanceOfResponseBase(value: object): value is ResponseBase {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ResponseBaseFromJSON(json: any): ResponseBase {
    return ResponseBaseFromJSONTyped(json, false);
}

export function ResponseBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBase {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function ResponseBaseToJSON(json: any): ResponseBase {
    return ResponseBaseToJSONTyped(json, false);
}

export function ResponseBaseToJSONTyped(value?: ResponseBase | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

