/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SessionCreate
 */
export interface SessionCreate {
    /**
     * 
     * @type {string}
     * @memberof SessionCreate
     */
    quizId?: string | null;
}

/**
 * Check if a given object implements the SessionCreate interface.
 */
export function instanceOfSessionCreate(value: object): value is SessionCreate {
    return true;
}

export function SessionCreateFromJSON(json: any): SessionCreate {
    return SessionCreateFromJSONTyped(json, false);
}

export function SessionCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'quizId': json['quiz_id'] == null ? undefined : json['quiz_id'],
    };
}

export function SessionCreateToJSON(json: any): SessionCreate {
    return SessionCreateToJSONTyped(json, false);
}

export function SessionCreateToJSONTyped(value?: SessionCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'quiz_id': value['quizId'],
    };
}

