/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SummaryPublic
 */
export interface SummaryPublic {
    /**
     * 
     * @type {string}
     * @memberof SummaryPublic
     */
    questionId: string;
    /**
     * 
     * @type {string}
     * @memberof SummaryPublic
     */
    topicId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SummaryPublic
     */
    summaryText: string;
    /**
     * 
     * @type {string}
     * @memberof SummaryPublic
     */
    emoji?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SummaryPublic
     */
    score?: number;
    /**
     * 
     * @type {string}
     * @memberof SummaryPublic
     */
    algorithm: string;
    /**
     * 
     * @type {string}
     * @memberof SummaryPublic
     */
    id: string;
}

/**
 * Check if a given object implements the SummaryPublic interface.
 */
export function instanceOfSummaryPublic(value: object): value is SummaryPublic {
    if (!('questionId' in value) || value['questionId'] === undefined) return false;
    if (!('summaryText' in value) || value['summaryText'] === undefined) return false;
    if (!('algorithm' in value) || value['algorithm'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function SummaryPublicFromJSON(json: any): SummaryPublic {
    return SummaryPublicFromJSONTyped(json, false);
}

export function SummaryPublicFromJSONTyped(json: any, ignoreDiscriminator: boolean): SummaryPublic {
    if (json == null) {
        return json;
    }
    return {
        
        'questionId': json['question_id'],
        'topicId': json['topic_id'] == null ? undefined : json['topic_id'],
        'summaryText': json['summary_text'],
        'emoji': json['emoji'] == null ? undefined : json['emoji'],
        'score': json['score'] == null ? undefined : json['score'],
        'algorithm': json['algorithm'],
        'id': json['id'],
    };
}

export function SummaryPublicToJSON(json: any): SummaryPublic {
    return SummaryPublicToJSONTyped(json, false);
}

export function SummaryPublicToJSONTyped(value?: SummaryPublic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'question_id': value['questionId'],
        'topic_id': value['topicId'],
        'summary_text': value['summaryText'],
        'emoji': value['emoji'],
        'score': value['score'],
        'algorithm': value['algorithm'],
        'id': value['id'],
    };
}

