/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Topic
 */
export interface Topic {
    /**
     * 
     * @type {string}
     * @memberof Topic
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Topic
     */
    questionId: string;
    /**
     * 
     * @type {string}
     * @memberof Topic
     */
    topic: string;
}

/**
 * Check if a given object implements the Topic interface.
 */
export function instanceOfTopic(value: object): value is Topic {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('questionId' in value) || value['questionId'] === undefined) return false;
    if (!('topic' in value) || value['topic'] === undefined) return false;
    return true;
}

export function TopicFromJSON(json: any): Topic {
    return TopicFromJSONTyped(json, false);
}

export function TopicFromJSONTyped(json: any, ignoreDiscriminator: boolean): Topic {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'questionId': json['question_id'],
        'topic': json['topic'],
    };
}

export function TopicToJSON(json: any): Topic {
    return TopicToJSONTyped(json, false);
}

export function TopicToJSONTyped(value?: Topic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'question_id': value['questionId'],
        'topic': value['topic'],
    };
}

