"""Remove Rating model

Revision ID: 1e9e0d2ec27e
Revises: 1090f5fdff68
Create Date: 2025-03-28 14:49:36.213034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '1e9e0d2ec27e'
down_revision: Union[str, None] = '1090f5fdff68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('quiz_id', sa.CHAR(length=32), nullable=False),
    sa.Column('question', sa.VARCHAR(), nullable=False),
    sa.Column('stars_given', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], name='fk_rating_quiz_id_quiz', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_rating')
    )
    # ### end Alembic commands ###
