"""Extend Topic model

Revision ID: c20474f7440c
Revises: f2758dafdfd3
Create Date: 2025-02-22 19:28:56.030860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'c20474f7440c'
down_revision: Union[str, None] = 'f2758dafdfd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answertopicassociation',
    sa.Column('answer_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('answer_id', 'topic_id')
    )
    op.drop_table('answer_topic')
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('algorithm', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=False))
        batch_op.alter_column('topic',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.alter_column('topic',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.drop_column('score')
        batch_op.drop_column('label')
        batch_op.drop_column('algorithm')

    op.create_table('answer_topic',
    sa.Column('answer_id', sa.CHAR(length=32), nullable=False),
    sa.Column('topic_id', sa.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], name='fk_answer_topic_answer_id_answer', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], name='fk_answer_topic_topic_id_topic', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('answer_id', 'topic_id', name='pk_answer_topic')
    )
    op.drop_table('answertopicassociation')
    # ### end Alembic commands ###
