"""Add sentiment analysis model

Revision ID: c4d88b0bd51b
Revises: 53b12b24e09d
Create Date: 2025-02-17 22:18:13.394465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'c4d88b0bd51b'
down_revision: Union[str, None] = '53b12b24e09d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentimentanalysis',
    sa.Column('answer_id', sa.Uuid(), nullable=False),
    sa.Column('algorithm', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('verdict', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('compound', sa.Float(), nullable=False),
    sa.Column('positive', sa.Float(), nullable=False),
    sa.Column('neutral', sa.Float(), nullable=False),
    sa.Column('negative', sa.Float(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentimentanalysis')
    # ### end Alembic commands ###
