name: Frontend Lint

on:
  workflow_dispatch:

#on:
#  push:
#    branches:
#      - 'main'
#    paths:
#      - 'frontend/**'
#  pull_request:
#    paths:
#      - 'frontend/**'

jobs:
  lint-frontend:
    name: eslint frontend
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install
        working-directory: ./frontend

      - name: Run ESLint
        run: bun lint
        working-directory: ./frontend

  prettier-frontend:
    name: Prettier frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install
        working-directory: ./frontend

      - name: Run Prettier
        run: bun prettier:check
        working-directory: ./frontend

  tsc-frontend:
    name: typescript frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install
        working-directory: ./frontend

      - name: tsc
        run: bun tsc -- --noEmit
        working-directory: ./frontend
